### ISSUE TITLE
Adding custom attribute handling

### ISSUE THREAD

**Issue by bdharrington7** [akhoury/html-md-optional_window#1]
Hey Aziz, 

I've come across this dilemma, where in my forum, we have quoting using blockquote tags; the quotes are converted correctly using this library, but there's this extra attribute "rel" that links to the user you're quoting:

```
<blockquote rel="quotedUser"> Something I said</blockquote>
```

 I looked around and didn't see anything indicating that this is a standard convention, so I didn't think it appropriate to make a PR on the original repo. I'm not even sure it belongs here, as it seems unique to a plugin on the Vanilla platform. Do you have any ideas how this could be handled?

**Comment by akhoury** [comment]
yea, `rel` is not a standard attribute, according to [specs](https://www.w3.org/wiki/HTML/Elements/blockquote)

I suggest manually pre-parsing i guess,
I hate to parse html manually, but here's a quick solution. Might run into issues if nested quotes. 

``` javascript
var re = /<blockquote\srel="(.+?)">(.+?)<\/blockquote>/gi;
function replaceQuotes (content) {
   if (!re.test(content)) return content;
   return content.replace(re, '@$1 said<br>') + content; // leave the html in, this is just a pre-process
}
```

or i guess it wouldn't hurt to support an optional attribute to `blockquote` if you want, 
you could support `'cite' || 'rel' || 'author'` or something like that

somewhere here: 
https://github.com/akhoury/html-md-optional_window/blob/master/src/md.coffee#L437

**Comment by bdharrington7** [comment]
Since the author hasn't merged your PR in months, would you consider keeping this repo open? 

-Brian

**Comment by akhoury** [comment]
sure.  i guess.
it's published on [npm](https://www.npmjs.com/package/html-md-optional_window) - might as well let it live.
don't appreciate the long name, but who cares
